// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/app/modules/login/views/login_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i14;

import 'package:dio/dio.dart' as _i4;
import 'package:flutter/material.dart' as _i13;
import 'package:fresh_leaf/app/modules/profile/controllers/profile_controller.dart'
    as _i16;
import 'package:fresh_leaf/core/controllers/app_settings_controller.dart'
    as _i12;
import 'package:fresh_leaf/core/models/app_notification.dart' as _i11;
import 'package:fresh_leaf/core/models/paginated_response.dart' as _i6;
import 'package:fresh_leaf/core/models/payment_method.dart' as _i19;
import 'package:fresh_leaf/core/models/user_address.dart' as _i17;
import 'package:fresh_leaf/core/models/user_profile.dart' as _i10;
import 'package:fresh_leaf/core/models/wallet.dart' as _i18;
import 'package:fresh_leaf/core/services/api_client.dart' as _i7;
import 'package:fresh_leaf/core/services/notification_service.dart' as _i5;
import 'package:fresh_leaf/core/services/storage_service.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_3<E> extends _i1.SmartFake implements _i3.RxList<E> {
  _FakeRxList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_4 extends _i1.SmartFake implements _i3.RxInt {
  _FakeRxInt_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_5 extends _i1.SmartFake
    implements _i5.NotificationService {
  _FakeNotificationService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponse_6<T> extends _i1.SmartFake
    implements _i6.PaginatedResponse<T> {
  _FakePaginatedResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_7<T> extends _i1.SmartFake implements _i3.Rx<T> {
  _FakeRx_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_8 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_9 extends _i1.SmartFake implements _i3.RxString {
  _FakeRxString_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  @override
  _i2.StorageService get storageService =>
      (super.noSuchMethod(
            Invocation.getter(#storageService),
            returnValue: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
            returnValueForMissingStub: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
          )
          as _i2.StorageService);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> getRequest(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequest,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #getRequest,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #getRequest,
                      [path],
                      {
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> postRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> postMultipart(
    String? path, {
    required _i4.FormData? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipart,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postMultipart,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postMultipart,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> putRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #putRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #putRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> patchRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #patchRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #patchRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<Map<String, dynamic>>> deleteRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #deleteRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #deleteRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i8.Future<_i4.Response<T>> externalRequest<T>(
    String? url, {
    String? method = 'GET',
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #externalRequest,
              [url],
              {
                #method: method,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i8.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i4.Response<T>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  @override
  bool get onboardingSeen =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingSeen),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get pinOrderVerification =>
      (super.noSuchMethod(
            Invocation.getter(#pinOrderVerification),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#themeMode),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#themeMode),
            ),
          )
          as String);

  @override
  bool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set userProfile(_i10.UserProfile? value) => super.noSuchMethod(
    Invocation.setter(#userProfile, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveOnboardingSeen({required bool? seen}) =>
      (super.noSuchMethod(
            Invocation.method(#saveOnboardingSeen, [], {#seen: seen}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveSecurityPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#saveSecurityPin, [pin]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> savePinOrderVerification({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#savePinOrderVerification, [], {
              #enabled: enabled,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveThemeMode(String? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [themeMode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveLocale(String? languageCode, String? countryCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocale, [languageCode, countryCode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveNotificationsEnabled({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotificationsEnabled, [], {
              #enabled: enabled,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i5.NotificationService {
  @override
  _i3.RxList<_i11.AppNotification> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _FakeRxList_3<_i11.AppNotification>(
              this,
              Invocation.getter(#notifications),
            ),
            returnValueForMissingStub: _FakeRxList_3<_i11.AppNotification>(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i3.RxList<_i11.AppNotification>);

  @override
  _i3.RxInt get unreadCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadCount),
            returnValue: _FakeRxInt_4(this, Invocation.getter(#unreadCount)),
            returnValueForMissingStub: _FakeRxInt_4(
              this,
              Invocation.getter(#unreadCount),
            ),
          )
          as _i3.RxInt);

  @override
  _i3.RxInt get unreadChatCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadChatCount),
            returnValue: _FakeRxInt_4(
              this,
              Invocation.getter(#unreadChatCount),
            ),
            returnValueForMissingStub: _FakeRxInt_4(
              this,
              Invocation.getter(#unreadChatCount),
            ),
          )
          as _i3.RxInt);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i5.NotificationService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i5.NotificationService>.value(
              _FakeNotificationService_5(this, Invocation.method(#init, [])),
            ),
            returnValueForMissingStub:
                _i8.Future<_i5.NotificationService>.value(
                  _FakeNotificationService_5(
                    this,
                    Invocation.method(#init, []),
                  ),
                ),
          )
          as _i8.Future<_i5.NotificationService>);

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> uploadToken() =>
      (super.noSuchMethod(
            Invocation.method(#uploadToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> fetchUnreadChatCount() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUnreadChatCount, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.PaginatedResponse<_i11.AppNotification>> getNotifications({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {#page: page}),
            returnValue:
                _i8.Future<_i6.PaginatedResponse<_i11.AppNotification>>.value(
                  _FakePaginatedResponse_6<_i11.AppNotification>(
                    this,
                    Invocation.method(#getNotifications, [], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i6.PaginatedResponse<_i11.AppNotification>>.value(
                  _FakePaginatedResponse_6<_i11.AppNotification>(
                    this,
                    Invocation.method(#getNotifications, [], {#page: page}),
                  ),
                ),
          )
          as _i8.Future<_i6.PaginatedResponse<_i11.AppNotification>>);

  @override
  _i8.Future<bool> markAsRead(int? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppSettingsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsController extends _i1.Mock
    implements _i12.AppSettingsController {
  @override
  _i3.Rx<_i13.ThemeMode> get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _FakeRx_7<_i13.ThemeMode>(
              this,
              Invocation.getter(#themeMode),
            ),
            returnValueForMissingStub: _FakeRx_7<_i13.ThemeMode>(
              this,
              Invocation.getter(#themeMode),
            ),
          )
          as _i3.Rx<_i13.ThemeMode>);

  @override
  _i3.Rx<_i14.Locale> get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeRx_7<_i14.Locale>(
              this,
              Invocation.getter(#locale),
            ),
            returnValueForMissingStub: _FakeRx_7<_i14.Locale>(
              this,
              Invocation.getter(#locale),
            ),
          )
          as _i3.Rx<_i14.Locale>);

  @override
  _i3.RxBool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: _FakeRxBool_8(
              this,
              Invocation.getter(#notificationsEnabled),
            ),
            returnValueForMissingStub: _FakeRxBool_8(
              this,
              Invocation.getter(#notificationsEnabled),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setThemeMode(
    _i13.ThemeMode? mode, {
    bool? syncToBackend = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setThemeMode,
              [mode],
              {#syncToBackend: syncToBackend},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLocale(
    _i14.Locale? value, {
    bool? syncToBackend = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setLocale,
              [value],
              {#syncToBackend: syncToBackend},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setNotificationsEnabled({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationsEnabled, [], {
              #enabled: enabled,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListener(_i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i15.Disposer);

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i14.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListenerId(Object? key, _i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i15.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileController extends _i1.Mock implements _i16.ProfileController {
  @override
  _i3.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_8(this, Invocation.getter(#isLoading)),
            returnValueForMissingStub: _FakeRxBool_8(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxString get userName =>
      (super.noSuchMethod(
            Invocation.getter(#userName),
            returnValue: _FakeRxString_9(this, Invocation.getter(#userName)),
            returnValueForMissingStub: _FakeRxString_9(
              this,
              Invocation.getter(#userName),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxString get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _FakeRxString_9(this, Invocation.getter(#email)),
            returnValueForMissingStub: _FakeRxString_9(
              this,
              Invocation.getter(#email),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxString get image =>
      (super.noSuchMethod(
            Invocation.getter(#image),
            returnValue: _FakeRxString_9(this, Invocation.getter(#image)),
            returnValueForMissingStub: _FakeRxString_9(
              this,
              Invocation.getter(#image),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxString get phone =>
      (super.noSuchMethod(
            Invocation.getter(#phone),
            returnValue: _FakeRxString_9(this, Invocation.getter(#phone)),
            returnValueForMissingStub: _FakeRxString_9(
              this,
              Invocation.getter(#phone),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxString get memberSince =>
      (super.noSuchMethod(
            Invocation.getter(#memberSince),
            returnValue: _FakeRxString_9(this, Invocation.getter(#memberSince)),
            returnValueForMissingStub: _FakeRxString_9(
              this,
              Invocation.getter(#memberSince),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxList<_i17.UserAddress> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: _FakeRxList_3<_i17.UserAddress>(
              this,
              Invocation.getter(#addresses),
            ),
            returnValueForMissingStub: _FakeRxList_3<_i17.UserAddress>(
              this,
              Invocation.getter(#addresses),
            ),
          )
          as _i3.RxList<_i17.UserAddress>);

  @override
  _i3.RxList<_i18.Wallet> get wallets =>
      (super.noSuchMethod(
            Invocation.getter(#wallets),
            returnValue: _FakeRxList_3<_i18.Wallet>(
              this,
              Invocation.getter(#wallets),
            ),
            returnValueForMissingStub: _FakeRxList_3<_i18.Wallet>(
              this,
              Invocation.getter(#wallets),
            ),
          )
          as _i3.RxList<_i18.Wallet>);

  @override
  _i3.RxList<_i19.PaymentMethod> get paymentMethods =>
      (super.noSuchMethod(
            Invocation.getter(#paymentMethods),
            returnValue: _FakeRxList_3<_i19.PaymentMethod>(
              this,
              Invocation.getter(#paymentMethods),
            ),
            returnValueForMissingStub: _FakeRxList_3<_i19.PaymentMethod>(
              this,
              Invocation.getter(#paymentMethods),
            ),
          )
          as _i3.RxList<_i19.PaymentMethod>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void setProfile(_i10.UserProfile? profile) => super.noSuchMethod(
    Invocation.method(#setProfile, [profile]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openOrders() =>
      (super.noSuchMethod(
            Invocation.method(#openOrders, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openWallet() =>
      (super.noSuchMethod(
            Invocation.method(#openWallet, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> preloadSubModules() =>
      (super.noSuchMethod(
            Invocation.method(#preloadSubModules, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListener(_i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i15.Disposer);

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i14.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListenerId(Object? key, _i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i15.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
