// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/core/services/ai_assistant_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i4;
import 'package:fresh_leaf/core/services/api_client.dart' as _i5;
import 'package:fresh_leaf/core/services/storage_service.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  @override
  _i2.StorageService get storageService =>
      (super.noSuchMethod(
            Invocation.getter(#storageService),
            returnValue: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
            returnValueForMissingStub: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
          )
          as _i2.StorageService);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> getRequest(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequest,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #getRequest,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #getRequest,
                      [path],
                      {
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> postRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> postMultipart(
    String? path, {
    required _i4.FormData? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipart,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postMultipart,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postMultipart,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> putRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #putRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #putRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> patchRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #patchRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #patchRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<Map<String, dynamic>>> deleteRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #deleteRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #deleteRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Response<T>> externalRequest<T>(
    String? url, {
    String? method = 'GET',
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #externalRequest,
              [url],
              {
                #method: method,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<T>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
