// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/app/modules/wallet_top_up/views/wallet_top_up_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i4;
import 'package:fresh_leaf/core/models/payment_session.dart' as _i5;
import 'package:fresh_leaf/core/models/user_profile.dart' as _i9;
import 'package:fresh_leaf/core/services/api_client.dart' as _i6;
import 'package:fresh_leaf/core/services/payment_session_service.dart' as _i10;
import 'package:fresh_leaf/core/services/storage_service.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentSession_3 extends _i1.SmartFake
    implements _i5.PaymentSession {
  _FakePaymentSession_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  @override
  _i2.StorageService get storageService =>
      (super.noSuchMethod(
            Invocation.getter(#storageService),
            returnValue: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
            returnValueForMissingStub: _FakeStorageService_0(
              this,
              Invocation.getter(#storageService),
            ),
          )
          as _i2.StorageService);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> getRequest(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequest,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #getRequest,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #getRequest,
                      [path],
                      {
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> postRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> postMultipart(
    String? path, {
    required _i4.FormData? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipart,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #postMultipart,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postMultipart,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> putRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #putRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #putRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> patchRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #patchRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #patchRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                        #onSendProgress: onSendProgress,
                        #onReceiveProgress: onReceiveProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<Map<String, dynamic>>> deleteRequest(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteRequest,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
              _FakeResponse_2<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #deleteRequest,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.Response<Map<String, dynamic>>>.value(
                  _FakeResponse_2<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #deleteRequest,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i7.Future<_i4.Response<Map<String, dynamic>>>);

  @override
  _i7.Future<_i4.Response<T>> externalRequest<T>(
    String? url, {
    String? method = 'GET',
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #externalRequest,
              [url],
              {
                #method: method,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i7.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #externalRequest,
                  [url],
                  {
                    #method: method,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Response<T>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  @override
  bool get onboardingSeen =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingSeen),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get pinOrderVerification =>
      (super.noSuchMethod(
            Invocation.getter(#pinOrderVerification),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#themeMode),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#themeMode),
            ),
          )
          as String);

  @override
  bool get notificationsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set userProfile(_i9.UserProfile? value) => super.noSuchMethod(
    Invocation.setter(#userProfile, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveOnboardingSeen({required bool? seen}) =>
      (super.noSuchMethod(
            Invocation.method(#saveOnboardingSeen, [], {#seen: seen}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveSecurityPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#saveSecurityPin, [pin]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> savePinOrderVerification({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#savePinOrderVerification, [], {
              #enabled: enabled,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveThemeMode(String? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [themeMode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveLocale(String? languageCode, String? countryCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocale, [languageCode, countryCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveNotificationsEnabled({required bool? enabled}) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotificationsEnabled, [], {
              #enabled: enabled,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PaymentSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentSessionService extends _i1.Mock
    implements _i10.PaymentSessionService {
  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<_i5.PaymentSession> createTopUpSession({
    required double? amount,
    required String? currency,
    required String? paymentMethodTypeCode,
    int? paymentMethodId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTopUpSession, [], {
              #amount: amount,
              #currency: currency,
              #paymentMethodTypeCode: paymentMethodTypeCode,
              #paymentMethodId: paymentMethodId,
            }),
            returnValue: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#createTopUpSession, [], {
                  #amount: amount,
                  #currency: currency,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#createTopUpSession, [], {
                  #amount: amount,
                  #currency: currency,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.PaymentSession>);

  @override
  _i7.Future<_i5.PaymentSession> createCheckoutSession({
    required double? amount,
    required String? paymentMethodTypeCode,
    int? paymentMethodId,
    List<Map<String, dynamic>>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [], {
              #amount: amount,
              #paymentMethodTypeCode: paymentMethodTypeCode,
              #paymentMethodId: paymentMethodId,
              #items: items,
            }),
            returnValue: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#createCheckoutSession, [], {
                  #amount: amount,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                  #items: items,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#createCheckoutSession, [], {
                  #amount: amount,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                  #items: items,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.PaymentSession>);

  @override
  _i7.Future<_i5.PaymentSession> getSessionStatus(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionStatus, [sessionId]),
            returnValue: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#getSessionStatus, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.PaymentSession>.value(
              _FakePaymentSession_3(
                this,
                Invocation.method(#getSessionStatus, [sessionId]),
              ),
            ),
          )
          as _i7.Future<_i5.PaymentSession>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
