// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/app/modules/cart/views/cart_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fresh_leaf/core/models/cart_item.dart' as _i6;
import 'package:fresh_leaf/core/models/cart_snapshot.dart' as _i3;
import 'package:fresh_leaf/core/services/cart_service.dart' as _i4;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartSnapshot_1 extends _i1.SmartFake implements _i3.CartSnapshot {
  _FakeCartSnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i4.CartService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<_i3.CartSnapshot> getCartSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#getCartSnapshot, []),
            returnValue: _i5.Future<_i3.CartSnapshot>.value(
              _FakeCartSnapshot_1(
                this,
                Invocation.method(#getCartSnapshot, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.CartSnapshot>.value(
              _FakeCartSnapshot_1(
                this,
                Invocation.method(#getCartSnapshot, []),
              ),
            ),
          )
          as _i5.Future<_i3.CartSnapshot>);

  @override
  _i5.Future<List<_i6.CartItem>> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i5.Future<List<_i6.CartItem>>.value(<_i6.CartItem>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.CartItem>>.value(
              <_i6.CartItem>[],
            ),
          )
          as _i5.Future<List<_i6.CartItem>>);

  @override
  _i5.Future<bool> addToCart(int? vendorInventoryId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [vendorInventoryId, quantity]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateCartItem(int? cartItemId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItem, [cartItemId, quantity]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeCartItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCartItem, [cartItemId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<int>?> checkout(
    int? addressId,
    int? paymentMethodId,
    int? paymentMethodTypeId,
    int? orderTypeId, {
    int? paymentCurrencyId,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkout,
              [addressId, paymentMethodId, paymentMethodTypeId, orderTypeId],
              {#paymentCurrencyId: paymentCurrencyId, #notes: notes},
            ),
            returnValue: _i5.Future<List<int>?>.value(),
            returnValueForMissingStub: _i5.Future<List<int>?>.value(),
          )
          as _i5.Future<List<int>?>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
