// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/app/modules/home/views/home_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:fresh_leaf/core/models/app_notification.dart' as _i11;
import 'package:fresh_leaf/core/models/cart_item.dart' as _i15;
import 'package:fresh_leaf/core/models/cart_snapshot.dart' as _i6;
import 'package:fresh_leaf/core/models/order.dart' as _i17;
import 'package:fresh_leaf/core/models/paginated_response.dart' as _i3;
import 'package:fresh_leaf/core/models/product_category.dart' as _i13;
import 'package:fresh_leaf/core/models/vendor_inventory.dart' as _i9;
import 'package:fresh_leaf/core/models/vendor_profile.dart' as _i10;
import 'package:fresh_leaf/core/repositories/home_repository.dart' as _i12;
import 'package:fresh_leaf/core/repositories/location_repository.dart' as _i5;
import 'package:fresh_leaf/core/services/cart_service.dart' as _i14;
import 'package:fresh_leaf/core/services/notification_service.dart' as _i4;
import 'package:fresh_leaf/core/services/order_service.dart' as _i16;
import 'package:fresh_leaf/core/services/product_service.dart' as _i7;
import 'package:fresh_leaf/core/services/wishlist_service.dart' as _i18;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedResponse_1<T> extends _i1.SmartFake
    implements _i3.PaginatedResponse<T> {
  _FakePaginatedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_2<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_3 extends _i1.SmartFake implements _i2.RxInt {
  _FakeRxInt_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_4 extends _i1.SmartFake
    implements _i4.NotificationService {
  _FakeNotificationService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationResult_5 extends _i1.SmartFake
    implements _i5.LocationResult {
  _FakeLocationResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartSnapshot_6 extends _i1.SmartFake implements _i6.CartSnapshot {
  _FakeCartSnapshot_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i7.ProductService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>> getProducts({
    int? categoryId,
    String? query,
    String? province,
    String? filter,
    int? page = 1,
    int? perPage = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #categoryId: categoryId,
              #query: query,
              #province: province,
              #filter: filter,
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>.value(
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #categoryId: categoryId,
                      #query: query,
                      #province: province,
                      #filter: filter,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>.value(
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #categoryId: categoryId,
                      #query: query,
                      #province: province,
                      #filter: filter,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>);

  @override
  _i8.Future<List<_i9.VendorInventory>> getProductBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySlug, [slug]),
            returnValue: _i8.Future<List<_i9.VendorInventory>>.value(
              <_i9.VendorInventory>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i9.VendorInventory>>.value(
                  <_i9.VendorInventory>[],
                ),
          )
          as _i8.Future<List<_i9.VendorInventory>>);

  @override
  _i8.Future<_i9.VendorInventory?> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i8.Future<_i9.VendorInventory?>.value(),
            returnValueForMissingStub: _i8.Future<_i9.VendorInventory?>.value(),
          )
          as _i8.Future<_i9.VendorInventory?>);

  @override
  _i8.Future<(_i10.VendorProfile?, _i3.PaginatedResponse<_i9.VendorInventory>)>
  getVendorProfile(int? id, {int? page = 1, int? perPage = 10}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVendorProfile,
              [id],
              {#page: page, #perPage: perPage},
            ),
            returnValue:
                _i8.Future<
                  (
                    _i10.VendorProfile?,
                    _i3.PaginatedResponse<_i9.VendorInventory>,
                  )
                >.value((
                  null,
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(
                      #getVendorProfile,
                      [id],
                      {#page: page, #perPage: perPage},
                    ),
                  ),
                )),
            returnValueForMissingStub:
                _i8.Future<
                  (
                    _i10.VendorProfile?,
                    _i3.PaginatedResponse<_i9.VendorInventory>,
                  )
                >.value((
                  null,
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(
                      #getVendorProfile,
                      [id],
                      {#page: page, #perPage: perPage},
                    ),
                  ),
                )),
          )
          as _i8.Future<
            (_i10.VendorProfile?, _i3.PaginatedResponse<_i9.VendorInventory>)
          >);

  @override
  _i8.Future<bool> createProduct(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [data]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  @override
  _i2.RxList<_i11.AppNotification> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _FakeRxList_2<_i11.AppNotification>(
              this,
              Invocation.getter(#notifications),
            ),
            returnValueForMissingStub: _FakeRxList_2<_i11.AppNotification>(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i2.RxList<_i11.AppNotification>);

  @override
  _i2.RxInt get unreadCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadCount),
            returnValue: _FakeRxInt_3(this, Invocation.getter(#unreadCount)),
            returnValueForMissingStub: _FakeRxInt_3(
              this,
              Invocation.getter(#unreadCount),
            ),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get unreadChatCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadChatCount),
            returnValue: _FakeRxInt_3(
              this,
              Invocation.getter(#unreadChatCount),
            ),
            returnValueForMissingStub: _FakeRxInt_3(
              this,
              Invocation.getter(#unreadChatCount),
            ),
          )
          as _i2.RxInt);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i4.NotificationService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i4.NotificationService>.value(
              _FakeNotificationService_4(this, Invocation.method(#init, [])),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.NotificationService>.value(
                  _FakeNotificationService_4(
                    this,
                    Invocation.method(#init, []),
                  ),
                ),
          )
          as _i8.Future<_i4.NotificationService>);

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> uploadToken() =>
      (super.noSuchMethod(
            Invocation.method(#uploadToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> fetchUnreadChatCount() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUnreadChatCount, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.PaginatedResponse<_i11.AppNotification>> getNotifications({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {#page: page}),
            returnValue:
                _i8.Future<_i3.PaginatedResponse<_i11.AppNotification>>.value(
                  _FakePaginatedResponse_1<_i11.AppNotification>(
                    this,
                    Invocation.method(#getNotifications, [], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.PaginatedResponse<_i11.AppNotification>>.value(
                  _FakePaginatedResponse_1<_i11.AppNotification>(
                    this,
                    Invocation.method(#getNotifications, [], {#page: page}),
                  ),
                ),
          )
          as _i8.Future<_i3.PaginatedResponse<_i11.AppNotification>>);

  @override
  _i8.Future<bool> markAsRead(int? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i12.HomeRepository {
  @override
  _i8.Future<List<_i13.ProductCategory>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i8.Future<List<_i13.ProductCategory>>.value(
              <_i13.ProductCategory>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i13.ProductCategory>>.value(
                  <_i13.ProductCategory>[],
                ),
          )
          as _i8.Future<List<_i13.ProductCategory>>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i5.LocationRepository {
  @override
  _i8.Future<_i5.LocationResult> reverseGeocode(
    double? latitude,
    double? longitude, {
    String? language = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reverseGeocode,
              [latitude, longitude],
              {#language: language},
            ),
            returnValue: _i8.Future<_i5.LocationResult>.value(
              _FakeLocationResult_5(
                this,
                Invocation.method(
                  #reverseGeocode,
                  [latitude, longitude],
                  {#language: language},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.LocationResult>.value(
              _FakeLocationResult_5(
                this,
                Invocation.method(
                  #reverseGeocode,
                  [latitude, longitude],
                  {#language: language},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.LocationResult>);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i14.CartService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i6.CartSnapshot> getCartSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#getCartSnapshot, []),
            returnValue: _i8.Future<_i6.CartSnapshot>.value(
              _FakeCartSnapshot_6(
                this,
                Invocation.method(#getCartSnapshot, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.CartSnapshot>.value(
              _FakeCartSnapshot_6(
                this,
                Invocation.method(#getCartSnapshot, []),
              ),
            ),
          )
          as _i8.Future<_i6.CartSnapshot>);

  @override
  _i8.Future<List<_i15.CartItem>> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i8.Future<List<_i15.CartItem>>.value(
              <_i15.CartItem>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i15.CartItem>>.value(
              <_i15.CartItem>[],
            ),
          )
          as _i8.Future<List<_i15.CartItem>>);

  @override
  _i8.Future<bool> addToCart(int? vendorInventoryId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [vendorInventoryId, quantity]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> updateCartItem(int? cartItemId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItem, [cartItemId, quantity]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeCartItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCartItem, [cartItemId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<int>?> checkout(
    int? addressId,
    int? paymentMethodId,
    int? paymentMethodTypeId,
    int? orderTypeId, {
    int? paymentCurrencyId,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkout,
              [addressId, paymentMethodId, paymentMethodTypeId, orderTypeId],
              {#paymentCurrencyId: paymentCurrencyId, #notes: notes},
            ),
            returnValue: _i8.Future<List<int>?>.value(),
            returnValueForMissingStub: _i8.Future<List<int>?>.value(),
          )
          as _i8.Future<List<int>?>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i16.OrderService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<Map<int, int>> getOrderCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderCounts, []),
            returnValue: _i8.Future<Map<int, int>>.value(<int, int>{}),
            returnValueForMissingStub: _i8.Future<Map<int, int>>.value(
              <int, int>{},
            ),
          )
          as _i8.Future<Map<int, int>>);

  @override
  _i8.Future<_i3.PaginatedResponse<_i17.Order>> getOrders({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {#page: page}),
            returnValue: _i8.Future<_i3.PaginatedResponse<_i17.Order>>.value(
              _FakePaginatedResponse_1<_i17.Order>(
                this,
                Invocation.method(#getOrders, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.PaginatedResponse<_i17.Order>>.value(
                  _FakePaginatedResponse_1<_i17.Order>(
                    this,
                    Invocation.method(#getOrders, [], {#page: page}),
                  ),
                ),
          )
          as _i8.Future<_i3.PaginatedResponse<_i17.Order>>);

  @override
  _i8.Future<_i17.Order?> getOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [id]),
            returnValue: _i8.Future<_i17.Order?>.value(),
            returnValueForMissingStub: _i8.Future<_i17.Order?>.value(),
          )
          as _i8.Future<_i17.Order?>);

  @override
  _i8.Future<bool> cancelOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [id]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> confirmReceipt(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#confirmReceipt, [id]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> payWithWallet(int? orderId, int? walletId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#payWithWallet, [orderId, walletId, pin]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> batchPayWithWallet(
    List<int>? orderIds,
    int? walletId,
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchPayWithWallet, [orderIds, walletId, pin]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String?> getInvoiceUrl(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getInvoiceUrl, [id]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WishlistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistService extends _i1.Mock implements _i18.WishlistService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>> getWishlist({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, [], {#page: page}),
            returnValue:
                _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>.value(
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(#getWishlist, [], {#page: page}),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>.value(
                  _FakePaginatedResponse_1<_i9.VendorInventory>(
                    this,
                    Invocation.method(#getWishlist, [], {#page: page}),
                  ),
                ),
          )
          as _i8.Future<_i3.PaginatedResponse<_i9.VendorInventory>>);

  @override
  _i8.Future<bool> toggleWishlist(int? vendorInventoryId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleWishlist, [vendorInventoryId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
