// Mocks generated by Mockito 5.4.6 from annotations
// in fresh_leaf/test/app/modules/wallet_top_up/controllers/wallet_top_up_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:fresh_leaf/app/modules/wallet/controllers/wallet_controller.dart'
    as _i6;
import 'package:fresh_leaf/core/models/payment_session.dart' as _i3;
import 'package:fresh_leaf/core/models/wallet.dart' as _i8;
import 'package:fresh_leaf/core/services/payment_session_service.dart' as _i4;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentSession_1 extends _i1.SmartFake
    implements _i3.PaymentSession {
  _FakePaymentSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_2 extends _i1.SmartFake implements _i2.RxString {
  _FakeRxString_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_3 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxDouble_4 extends _i1.SmartFake implements _i2.RxDouble {
  _FakeRxDouble_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_5<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentSessionService extends _i1.Mock
    implements _i4.PaymentSessionService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<_i3.PaymentSession> createTopUpSession({
    required double? amount,
    required String? currency,
    required String? paymentMethodTypeCode,
    int? paymentMethodId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTopUpSession, [], {
              #amount: amount,
              #currency: currency,
              #paymentMethodTypeCode: paymentMethodTypeCode,
              #paymentMethodId: paymentMethodId,
            }),
            returnValue: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#createTopUpSession, [], {
                  #amount: amount,
                  #currency: currency,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#createTopUpSession, [], {
                  #amount: amount,
                  #currency: currency,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PaymentSession>);

  @override
  _i5.Future<_i3.PaymentSession> createCheckoutSession({
    required double? amount,
    required String? paymentMethodTypeCode,
    int? paymentMethodId,
    List<Map<String, dynamic>>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [], {
              #amount: amount,
              #paymentMethodTypeCode: paymentMethodTypeCode,
              #paymentMethodId: paymentMethodId,
              #items: items,
            }),
            returnValue: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#createCheckoutSession, [], {
                  #amount: amount,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                  #items: items,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#createCheckoutSession, [], {
                  #amount: amount,
                  #paymentMethodTypeCode: paymentMethodTypeCode,
                  #paymentMethodId: paymentMethodId,
                  #items: items,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PaymentSession>);

  @override
  _i5.Future<_i3.PaymentSession> getSessionStatus(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionStatus, [sessionId]),
            returnValue: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#getSessionStatus, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.PaymentSession>.value(
              _FakePaymentSession_1(
                this,
                Invocation.method(#getSessionStatus, [sessionId]),
              ),
            ),
          )
          as _i5.Future<_i3.PaymentSession>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WalletController].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletController extends _i1.Mock implements _i6.WalletController {
  @override
  _i2.RxString get selectedCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCurrency),
            returnValue: _FakeRxString_2(
              this,
              Invocation.getter(#selectedCurrency),
            ),
            returnValueForMissingStub: _FakeRxString_2(
              this,
              Invocation.getter(#selectedCurrency),
            ),
          )
          as _i2.RxString);

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#isLoading)),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isRefreshing =>
      (super.noSuchMethod(
            Invocation.getter(#isRefreshing),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#isRefreshing)),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#isRefreshing),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isBalanceVisible =>
      (super.noSuchMethod(
            Invocation.getter(#isBalanceVisible),
            returnValue: _FakeRxBool_3(
              this,
              Invocation.getter(#isBalanceVisible),
            ),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#isBalanceVisible),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxDouble get khrBalance =>
      (super.noSuchMethod(
            Invocation.getter(#khrBalance),
            returnValue: _FakeRxDouble_4(this, Invocation.getter(#khrBalance)),
            returnValueForMissingStub: _FakeRxDouble_4(
              this,
              Invocation.getter(#khrBalance),
            ),
          )
          as _i2.RxDouble);

  @override
  _i2.RxDouble get usdBalance =>
      (super.noSuchMethod(
            Invocation.getter(#usdBalance),
            returnValue: _FakeRxDouble_4(this, Invocation.getter(#usdBalance)),
            returnValueForMissingStub: _FakeRxDouble_4(
              this,
              Invocation.getter(#usdBalance),
            ),
          )
          as _i2.RxDouble);

  @override
  _i2.RxList<_i6.WalletTransaction> get khrTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#khrTransactions),
            returnValue: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#khrTransactions),
            ),
            returnValueForMissingStub: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#khrTransactions),
            ),
          )
          as _i2.RxList<_i6.WalletTransaction>);

  @override
  _i2.RxList<_i6.WalletTransaction> get usdTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#usdTransactions),
            returnValue: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#usdTransactions),
            ),
            returnValueForMissingStub: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#usdTransactions),
            ),
          )
          as _i2.RxList<_i6.WalletTransaction>);

  @override
  _i2.RxBool get khrHasMore =>
      (super.noSuchMethod(
            Invocation.getter(#khrHasMore),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#khrHasMore)),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#khrHasMore),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get usdHasMore =>
      (super.noSuchMethod(
            Invocation.getter(#usdHasMore),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#usdHasMore)),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#usdHasMore),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isLoadingMoreTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingMoreTransactions),
            returnValue: _FakeRxBool_3(
              this,
              Invocation.getter(#isLoadingMoreTransactions),
            ),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#isLoadingMoreTransactions),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get hasLoadedWallets =>
      (super.noSuchMethod(
            Invocation.getter(#hasLoadedWallets),
            returnValue: _FakeRxBool_3(
              this,
              Invocation.getter(#hasLoadedWallets),
            ),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#hasLoadedWallets),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxDouble get activeBalance =>
      (super.noSuchMethod(
            Invocation.getter(#activeBalance),
            returnValue: _FakeRxDouble_4(
              this,
              Invocation.getter(#activeBalance),
            ),
            returnValueForMissingStub: _FakeRxDouble_4(
              this,
              Invocation.getter(#activeBalance),
            ),
          )
          as _i2.RxDouble);

  @override
  _i2.RxList<_i6.WalletTransaction> get activeTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#activeTransactions),
            returnValue: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#activeTransactions),
            ),
            returnValueForMissingStub: _FakeRxList_5<_i6.WalletTransaction>(
              this,
              Invocation.getter(#activeTransactions),
            ),
          )
          as _i2.RxList<_i6.WalletTransaction>);

  @override
  _i2.RxBool get activeHasMore =>
      (super.noSuchMethod(
            Invocation.getter(#activeHasMore),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#activeHasMore)),
            returnValueForMissingStub: _FakeRxBool_3(
              this,
              Invocation.getter(#activeHasMore),
            ),
          )
          as _i2.RxBool);

  @override
  String get activeSymbol =>
      (super.noSuchMethod(
            Invocation.getter(#activeSymbol),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#activeSymbol),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#activeSymbol),
            ),
          )
          as String);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> onReady() =>
      (super.noSuchMethod(
            Invocation.method(#onReady, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setCurrency(String? currency) => super.noSuchMethod(
    Invocation.method(#setCurrency, [currency]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleBalanceVisibility() => super.noSuchMethod(
    Invocation.method(#toggleBalanceVisibility, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> refreshWallets() =>
      (super.noSuchMethod(
            Invocation.method(#refreshWallets, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchWallets({bool? showError = true}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWallets, [], {#showError: showError}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchTransactions({
    required int? walletId,
    required String? currencyCode,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, [], {
              #walletId: walletId,
              #currencyCode: currencyCode,
              #page: page,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTransactions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> applyWallets(List<_i8.Wallet>? wallets) =>
      (super.noSuchMethod(
            Invocation.method(#applyWallets, [wallets]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListener(_i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i9.Disposer);

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i10.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListenerId(Object? key, _i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i9.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
