final class AppRoutes {
  AppRoutes._();

  static const onboarding = '/onboarding';
  static const networkCheck = '/network_check';
  static const login = '/login';
  static const register = '/register';
  static const dashboard = '/dashboard';
  static const home = '/home';
  static const splash = '/splash';
  static const search = '/search';
  static const cart = '/cart';
  static const checkout = '/checkout';
  static const aiAssistant = '/ai_assistant';
  static const supportTickets = '/support_tickets';
  static const supportChat = '/support_chat';
  static const orders = '/orders';
  static const profile = '/profile';
  static const productDetail = '/product_detail';
  static const vendorProfile = '/vendor_profile';
  static const productList = '/product_list';
  static const orderDetail = '/order_detail';
  static const notifications = '/notifications';
  static const notificationDetail = '/notification_detail';
  static const personalDetails = '/personal_details';
  static const settings = '/settings';
  static const securitySettings = '/security_settings';
  static const addresses = '/addresses';
  static const addressesEdit = '/addresses_edit';
  static const pinSecurity = '/pin_security';
  static const pinPasswordVerification = '/pin_password_verification';
  static const pinVerification = '/pin_verification';
  static const wishlist = '/wishlist';
  static const paymentMethods = '/payment_methods';
  static const paymentMethodsAdd = '/payment_methods_add';
  static const orderWalletPayment = '/order-wallet-payment';
  static const orderExternalPayment = '/order-external-payment';
  static const helpCenter = '/help_center';
  static const privacyTerms = '/privacy_terms';
  static const wallet = '/wallet';
  static const walletTopUp = '/wallet_top_up';
  static const walletTopUpPayment = '/wallet_top_up_payment';
  static const walletTopUpSuccess = '/wallet_top_up_success';
  static const walletTransactions = '/wallet_transactions';
  static const paymentQr = '/payment_qr';
}
